import '../../../components/top-bar/top-bar'
import '../../../components/sidebar/sidebar'
import '../../../components/nav/nav'
import '../../../components/select/select'
import '../../../components/date-select/date-select'
import '../../../components/reviews/reviews'
import '../../../components/btn/btn'
import '../../../components/select-input/select-input'
